name: Compilar IPA 3105 (Sin Firmar)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Descargar Repositorio
      uses: actions/checkout@v4
      
    - name: Seleccionar version de Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.4.app
      
    - name: Compilar Proyecto de iOS (Omitiendo Firmas)
      run: |
        xcodebuild -project ThreeOneOSFive.xcodeproj \
                   -scheme ThreeOneOSFive \
                   -configuration Release \
                   -sdk iphoneos \
                   CODE_SIGNING_ALLOWED=NO \
                   CODE_SIGNING_REQUIRED=NO \
                   CODE_SIGN_IDENTITY="" \
                   CODE_SIGN_ENTITLEMENTS="" \
                   archive -archivePath ./build/ThreeOneOSFive.xcarchive
                   
    - name: Generar Contenedor IPA Manual
      run: |
        mkdir -p ./build/output/Payload
        cp -r ./build/ThreeOneOSFive.xcarchive/Products/Applications/*.app ./build/output/Payload/
        cd ./build/output
        zip -r ThreeOneOSFive_Unsigned.ipa Payload
        rm -rf Payload
        
    - name: Subir IPA Sin Firmar a GitHub
      uses: actions/upload-artifact@v4
      with:
        name: ThreeOneOSFive-Unsigned-IPA
        path: ./build/output/*.ipa
        retention-days: 30
